### ISSUE TITLE
some questions about CELLO benchmark

### ISSUE THREAD

**Issue by onlyonewater** [OpenCausaLab/CELLO#1]
Hi, authors, thanks for your promising works about Large Vision-Language Models Causality.  After carefully reading your paper, I have a question about the causal graph extraction process, which is converted through the scene graph. In my understanding, the causal graph is a Directed Acyclic Graph (DAG), but almost all the scene graphs are the Undirected Graphs. 

So how do you determine the direction of the graph in your benchmark? And I check your released dataset, for example,

"edges": [[3749557, 2037998, {"relation": "ON"}]

does the obj id 3749557 cause the obj id 2037998? or is it the other way round?

**Comment by chenmeiqii** [comment]
hi, sorry for the late reply. The causal graphs are indeed DAGs. For the example "edges": [[3749557, 2037998, {"relation": "ON"}], it means "obj 2037998 ON obj 3749557" and "obj  3749557 causes (the state of) obj 2037998"
